/* tslint:disable */
/* eslint-disable */
/**
 * Time Tracking API
 * REST API for time tracking, organizations, work schedules, absences and holidays.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

